services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            - QUEUE_CONNECTION=redis
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=laravel
            - DB_USERNAME=postgres
            - DB_PASSWORD=secret
        depends_on:
            - db
            - redis
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: laravel-web
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: postgres:15-alpine
        container_name: laravel-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel
        ports:
            - "127.0.0.1:5432:5432"

    redis:
        image: redis:alpine
        container_name: laravel-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel

    queue-worker:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: laravel-queue
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - db
            - redis
        command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
        networks:
            - laravel

volumes:
    pgdata:

networks:
    laravel:
        driver: bridge
