version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel
        depends_on:
            - redis
        environment:
            - QUEUE_CONNECTION=redis

    web:
        image: nginx:alpine
        container_name: laravel-web
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - app

    redis:
        image: redis:alpine
        container_name: laravel-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel

    queue-worker:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: laravel-queue
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel
        depends_on:
            - redis
        command: php artisan queue:work --sleep=3 --tries=3 --timeout=90

networks:
    laravel:
        driver: bridge
